service: okta-nodejs-aws-lambda-example

package:
  exclude:
    - __tests__/**
    - __mocks__/**
    - test/**
    - .vscode/**
    - README.md
    - '*.KEEP'
    - functions/**
    - resources/**
    - package.json
    - package-lock.json
    - config.js

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  logRetentionInDays: 1
functions:
  app:
    handler: index.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true